services:
  fridge-backend:
    build: .
    container_name: fridge-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: neon

      SPRING_DATASOURCE_PASSWORD: ${FRIDGE_NEON_DB_PASSWORD}
